from components.character import Character
from components.wall import Wall
from components.floor import Floor
from components.single_item import SingleItem
from components.chest import Chest
from components.coin import Coin
from components.flask import Flask
from components.doors import Doors
from components.weapon import Weapon
